export const SET_APP_CONTEXT = 'SET_APP_CONTEXT';
export const CLEAR_APP_CONTEXT = 'CLEAR_APP_CONTEXT';
export const SET_USER_LOGGED_ID = 'SET_USER_LOGGED_ID';
export const SET_USER_INFO = 'SET_USER_INFO';
export const CLOSE_SESSION = 'CLOSE_SESSION';
